changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Infrastructure
      labels:
        - ci
        - infrastructure
        - dependencies
    - title: Other Changes
      labels:
        - "*"
